version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest # cf. https://github.com/JonasAlfredsson/docker-nginx-certbot
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    container_name: nginx-proxy

volumes:
  nginx_secrets:

networks:
  default:
    name: nginx-proxy
    driver: bridge